# File: .streamlit/secrets.toml
# Aggiungi questo alla tua repo apes-suna-scouting/streamlit-app/.streamlit/secrets.toml

GOOGLE_CSE_API_KEY = "AIzaSyDMHxjFOFjK3h9LMKOiFL7RMiYolG7GCDMI"
GOOGLE_CSE_ID = "c12f53951c8884cfd"
